### ISSUE TITLE
Every thumb has video icon

### ISSUE THREAD

**Issue by kgnfth** [haiafara/vue-it-bigger#131]
my setup is like this

```js
    const matchingAlbums = await this.$strapi.find('albums', {
      slug: this.$route.params.slug,
    })
    const images = []
    matchingAlbums[0].media.forEach(function (item) {
      if (item.ext === '.mp4') {
        images.push({
          thumb: getStrapiMedia(`${item.formats.small.url}`),
          thumb_small: item.formats.thumbnail
            ? getStrapiMedia(`${item.formats.thumbnail.url}`)
            : getStrapiMedia(`${item.formats.small.url}`),
          width: item.formats.small.width,
          height: item.formats.small.height,
          type: 'video',
          sources: [
            {
              src: getStrapiMedia(`${item.url}`),
              type: 'video/mp4',
            },
          ],
        })
      } else {
        images.push({
          thumb: getStrapiMedia(`${item.formats.small.url}`),
          thumb_small: item.formats.thumbnail
            ? getStrapiMedia(`${item.formats.thumbnail.url}`)
            : getStrapiMedia(`${item.formats.small.url}`),
          width: item.width,
          height: item.height,
          type: 'image',
          src: getStrapiMedia(`${item.url}`),
        })
      }
    })

    this.images = images
```

then i use this
`<LightBox ref="lightbox" :media="images" :show-light-box="false"></LightBox>`

**Comment by janosrusiczki** [comment]
OK, but what's the problem?

**Comment by kgnfth** [comment]
> OK, but what's the problem?

thumb for pictures has video icon

**Comment by janosrusiczki** [comment]
OK, I identified the problem, will be pushing out a fix later today.

**Comment by kgnfth** [comment]
@janosrusiczki Thanks!

**Comment by janosrusiczki** [comment]
@kgnfth Just released version 0.2.2 with the problem you reported fixed. If possible please upgrade and report back, thank you.

**Comment by kgnfth** [comment]
Yes its fixed. i have one more question, how can we change the video player to [plyr](https://github.com/sampotts/plyr)

**Comment by janosrusiczki** [comment]
> Yes its fixed. i have one more question, how can we change the video player to [plyr](https://github.com/sampotts/plyr)

I totally missed your comment in March. Did you find a solution? If not I will look into it, but I'm not 100% sure yet that I want vue-it-bigger to depend on plyr. :smile:
