### ISSUE TITLE
Allow YouTube embeds

### ISSUE THREAD

**Issue by janosrusiczki** [haiafara/vue-it-bigger#24]

**Comment by solamichealolawale** [comment]
Is this working now?

**Comment by janosrusiczki** [comment]
Yes, I have to fix some minor issues and it is good to merge.

**Comment by solamichealolawale** [comment]
Okay. the last time I tried using youtube and vimeo, it's not working. So I don't know if I can re-install the package and check it out again

**Comment by janosrusiczki** [comment]
It's not merged / released yet, I will let you know in this thread when it is.

**Comment by solamichealolawale** [comment]
I hope it'll be released soon. Thanks for the good work.

**Comment by solamichealolawale** [comment]
Any update on this?

**Comment by janosrusiczki** [comment]
@solamichealolawale the version with YouTube embedding enabled is finally out.

**Comment by solamichealolawale** [comment]
Yes. Thanks for the amazing package.
Apart from the bug concerning the video still playing after the popup is closed, I don't know if I can help work on options like
`autoplay`,`muted ` etc for youtube embed sir

**Comment by janosrusiczki** [comment]
I've looked into it, it involves enabling the YouTube JS API but I decided to release the version with the embedding and add these later. Of course, if you submit a pull request I will happily look at it. :smile:
